In [4]:
#HERE WE WILL IMPORT ALL THE LIBRARIES WE MAY NEED.

import pandas as pd 
import numpy as np
import requests
import json
from bs4 import BeautifulSoup

IMPORT THE DATABASE FROM :( https://datos.madrid.es/nuevoMadrid/swagger-ui-master-2.2.10/dist/index.html?url=/egobfiles/api.datos.madrid.es.json )

Inside this document i have to find the dataset called: "Sedes: Centros con espacios deportivos", and when we found this dataset we have the get the first three columns, and this three will be part of our final table.

- Para poder leer el archivo que contiene la url tenemos que utilizar la libreria requests y los metodos de esta libreria, en concreto el metodo(requests.get), despues vamos a usar la libreria BeautifulSoup, que nos parseara el contenido que tenemos que usar nosotros) mirar bien para que sirve la libreria de BeautifulSoup.

- BeautifulSoup = es una libreria de python que nos permite extraer informacion de contenido en formato HTML o XML, para poder acceder al contenido, previamente hemos tenido que usar la libreria requests, para traernos la url donde tenemos la informacion, y lo que haremos sera:

 variable que queramos = requests.get("url donde tenemos toda la informacion")
 soup(le podemos poner como queramos pero le ponemos soup porque es la sopa donde vamos a tener todos los datos) = beautifulsoup(variable que queramos(donde nos hemos traido la url).content, "html o xml parser"(tendremos que poner el tipo de archivo que tenemos, si es html o xml))

In [72]:
#SUPER IMPORTANTE PARA SABER CUAL ES LA RUTA RELATIVA DE UN ARCHIVO PARA ABRIRLO DESPUES COMO UN CSV O JSON.
#MUY IMPORTANTE.
os.listdir("../DATA")

['212808-0-espacio-deporte.csv',
 'bicimad_stations.json',
 'bicipark_stations.json']

In [73]:
#IMPORTAMOS EL ARCHIVO DE SQL QUE HEMOS GUARDADO COMO UN .JSON() LA PRIMERA SE LLAMA BICIMAD_STATIONS.JSON


dataframe_bicimadstations = pd.read_json("../DATA/bicimad_stations.json")
dataframe_bicimadstations

,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry_type,geometry_coordinates
0,1,Puerta del Sol A,2,1a,Puerta del Sol nº 1,1,0,30,15,11,0,Point,"[-3.7018341, 40.4172137]"
1,2,Puerta del Sol B,1,1b,Puerta del Sol nº 1,1,0,30,22,4,0,Point,"[-3.701602938060457, 40.41731271011562]"
2,3,Miguel Moya,2,2,Calle Miguel Moya nº 1,1,0,24,12,11,0,Point,"[-3.7058415, 40.4205886]"
3,4,Plaza Conde Suchil,0,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,4,11,0,Point,"[-3.7069171, 40.4302937]"
4,5,Malasaña,2,4,Calle Manuela Malasaña nº 5,1,0,24,12,12,0,Point,"[-3.7025875, 40.4285524]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,266,Ciudad Universitaria 1,0,258,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,0,24,0,Point,"[-3.72699, 40.44375]"
260,267,Ciudad Universitaria 2,2,259,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,12,12,0,Point,"[-3.72693, 40.44342]"
261,268,Facultad Biología,2,260,Calle José Antonio Novais frente al nº 12,1,0,24,9,14,0,Point,"[-3.7272945, 40.4483322]"
262,269,Facultad Derecho,0,261,Avenida Complutense nº 23,1,0,24,5,18,0,Point,"[-3.72937, 40.45109]"
263,270,Zurbano,0,247,Calle Zurbano nº 90,1,0,24,6,15,0,Point,"[-3.69281, 40.43837]"

In [74]:
#AHORA TENEMOS QUE SEPARAR LA LATITUD Y LONGITUD EN DOS COLUMNAS PARA PODER CRUZARLA CON LA TABLA QUE ME HA TOCADO:

dataframe_bicimadstations #esta es la tabla que tenemos en la que la ultima columna tenemos que separarla en dos.

dataframe_bicimadstations['LONGITUD'] = [float(index.split(',')[0].replace("[", "")) for index in dataframe_bicimadstations['geometry_coordinates']]
    
dataframe_bicimadstations['LATITUD'] = [float(index.split(',')[1].replace("]", "")) for index in dataframe_bicimadstations['geometry_coordinates']]

#YA HEMOS DIVIDIDO LA COLUMNA FINAL EN DOS COLUMNAS UNA LLAMADA LATITUD Y OTRA LLAMADA LONGITUD.

dataframe_bicimadstations  #AQUI TENEMOS LA COMPROBACION DE QUE LA ULTIMA COLUMNA LA HEMOS SEPARADO EN OTRAS DOS COLUMNAS.

,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry_type,geometry_coordinates,LONGITUD,LATITUD
0,1,Puerta del Sol A,2,1a,Puerta del Sol nº 1,1,0,30,15,11,0,Point,"[-3.7018341, 40.4172137]",-3.701834,40.417214
1,2,Puerta del Sol B,1,1b,Puerta del Sol nº 1,1,0,30,22,4,0,Point,"[-3.701602938060457, 40.41731271011562]",-3.701603,40.417313
2,3,Miguel Moya,2,2,Calle Miguel Moya nº 1,1,0,24,12,11,0,Point,"[-3.7058415, 40.4205886]",-3.705842,40.420589
3,4,Plaza Conde Suchil,0,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,4,11,0,Point,"[-3.7069171, 40.4302937]",-3.706917,40.430294
4,5,Malasaña,2,4,Calle Manuela Malasaña nº 5,1,0,24,12,12,0,Point,"[-3.7025875, 40.4285524]",-3.702587,40.428552
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,266,Ciudad Universitaria 1,0,258,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,0,24,0,Point,"[-3.72699, 40.44375]",-3.726990,40.443750
260,267,Ciudad Universitaria 2,2,259,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,12,12,0,Point,"[-3.72693, 40.44342]",-3.726930,40.443420
261,268,Facultad Biología,2,260,Calle José Antonio Novais frente al nº 12,1,0,24,9,14,0,Point,"[-3.7272945, 40.4483322]",-3.727295,40.448332
262,269,Facultad Derecho,0,261,Avenida Complutense nº 23,1,0,24,5,18,0,Point,"[-3.72937, 40.45109]",-3.729370,40.451090
263,270,Zurbano,0,247,Calle Zurbano nº 90,1,0,24,6,15,0,Point,"[-3.69281, 40.43837]",-3.692810,40.438370

In [75]:
#VAMOS A CREAR UN DATAFRAME SOLO CON LAS COLUMNAS QUE VAMOS A NECESITAR PARA COMPARAR CON LA TABLA QUE ME HA TOCADO A MI:
from shapely.geometry import Point
import geopandas as gpd   # conda install -c conda-forge geopandas

def to_mercator(lat, long):
    # transform latitude/longitude data in degrees to pseudo-mercator coordinates in metres
    c = gpd.GeoSeries([Point(lat, long)], crs=4326)
    c = c.to_crs(3857)
    return c


dataframe_bicis = pd.DataFrame(dataframe_bicimadstations[["name","address","LATITUD","LONGITUD"]])
dataframe_bicis["DISTANCIA_BICIS"] = dataframe_bicis.apply(lambda x : to_mercator(x["LATITUD"],x["LONGITUD"]),axis=1)
dataframe_bicis

#CUANDO QUEREMOS PILLAR MAS DE UNA COLUMNA VAMOS A TENER QUE PONER DOS CORCHETES, MUCHO CUIDADO.
#TENEMOS QUE COMPROBAR QUE TENEMOS EL MISMO NUMERO DE FILAS QUE EL ORIGINAL YA QUE ESO NO LO HEMOS MODIFICADO
#LA COLUMNA DEL INDEX ME LA PILLA DIRECTAMENTE.
dataframe_bicis

,name,address,LATITUD,LONGITUD,DISTANCIA_BICIS
0,Puerta del Sol A,Puerta del Sol nº 1,40.417214,-3.701834,POINT (4499223.648366921 -412373.2851572837)
1,Puerta del Sol B,Puerta del Sol nº 1,40.417313,-3.701603,POINT (4499234.670122574 -412347.498528782)
2,Miguel Moya,Calle Miguel Moya nº 1,40.420589,-3.705842,POINT (4499599.340516399 -412820.3206106317)
3,Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,40.430294,-3.706917,POINT (4500679.707306497 -412940.3068148262)
4,Malasaña,Calle Manuela Malasaña nº 5,40.428552,-3.702587,POINT (4500485.866677178 -412457.3286497012)
...,...,...,...,...,...
259,Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,40.443750,-3.726990,POINT (4502177.655770458 -415179.5220676512)
260,Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,40.443420,-3.726930,POINT (4502140.920338497 -415172.8287427756)
261,Facultad Biología,Calle José Antonio Novais frente al nº 12,40.448332,-3.727295,POINT (4502687.743941171 -415213.4906984274)
262,Facultad Derecho,Avenida Complutense nº 23,40.451090,-3.729370,POINT (4502994.74083288 -415445.024322674)
263,Zurbano,Calle Zurbano nº 90,40.438370,-3.692810,POINT (4501578.756909991 -411366.6317244973)

In [90]:
os.listdir("../DATA")

['dataframe_bicis.csv',
 '.DS_Store',
 '212808-0-espacio-deporte.csv',
 'dataframe_total2.csv',
 'bicimad_stations.json',
 'bicipark_stations.json',
 'dataframe_sedes.csv']

In [78]:
#AHORA TENEMOS QUE IMPORTAR LA TABLA QUE TENEMOS QUE USAR DEL AYUNTAMIENTO DE MADRID:
#NOS LA HEMOS DESCARGADO COMO UN CSV, ENTONCES HACEMOS LO MISMO DE ANTES PERO CON PD.READ_CSV


dataframe_centrosdeportivos = pd.read_csv("../DATA/212808-0-espacio-deporte.csv", delimiter = ";")
dataframe_centrosdeportivos 

dataframe_centrosdeportivos.head()


#columnas que vamos a necesitar de esta tabla: ["NOMBRE" , "NOMBRE-VIA" , "DISTRITO" , "LATITUD" , "LONGITUD"]
#El resto de columnas no no valen para nada.

,PK,NOMBRE,DESCRIPCION-ENTIDAD,HORARIO,EQUIPAMIENTO,TRANSPORTE,DESCRIPCION,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 30
0,181447,Campo de Golf del Centro Nacional de Golf,NaN,NaN,NaN,"Bus: 67, 82, 49 Metro: Lacoma (línea 7)",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,ARROYO DEL MONTE,...,FUENCARRAL-EL PARDO,437683.0,4481905.0,40.485508,-3.735279,913 769 060,NaN,info@centronacionalgolf.com,/contenido/entidadesYorganismos/CentrosEspacio...,
1,4670,Campo de Golf del Club de Golf Olivar de la Hi...,NaN,NaN,NaN,"Metro: Feria de Madrid (línea 8) Bus: 122, 112",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,VIA DE DUBLIN,...,BARAJAS,448286.0,4479796.0,40.465351,-3.611293,917 211 889,NaN,go@golfolivar.com,/contenido/entidadesYorganismos/CentrosEspacio...,
2,56494,Campos de Fútbol Ernesto Cotorruelo,Sede de la Real Federación de Fútbol de Madrid.,NaN,NaN,"Metro: Abrantes (línea 11). Bus: 116, E1.",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,VIA LUSITANA,...,CARABANCHEL,438529.0,4470323.0,40.381231,-3.724179,917 791 610 (Real Federación de Fútbol de Madrid),NaN,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,
3,7381184,Centro Comercial Dreams - Palacio Municipal de...,NaN,NaN,NaN,"Metro: Canillas (línea 4). Bus: 120, 112, 122...",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,SILVANO,...,HORTALEZA,446103.0,4479332.0,40.462913,-3.635734,917 160 400,NaN,info@palaciodehielo.com,/contenido/entidadesYorganismos/CentrosEspacio...,
4,7081762,Centro de Alto Rendimiento del Consejo Superio...,NaN,NaN,NaN,"Bus: 46, U, 160, 161. Bicimad: Estación 257 (...",NaN,3,http://www.madrid.es/sites/v/index.jsp?vgnextc...,MARTIN FIERRO,...,MONCLOA-ARAVACA,437920.0,4476498.0,40.436812,-3.731957,915 896 700 (centralita) / 915 896 938 (inform...,915 896 847,NaN,/contenido/entidadesYorganismos/CentrosEspacio...,

In [79]:
#VAMOS A QUEDARNOS SOLO CON LAS COLUMNAS QUE NOS INTERESAN DE LA SEGUNDA TABLA, TABLA DE LA COMUNIDAD DE MADRID.

dataframe_sedes = pd.DataFrame(dataframe_centrosdeportivos[["NOMBRE" , "NOMBRE-VIA" , "DISTRITO" , "LATITUD" , "LONGITUD"]] )


def to_mercator(lat, long):
    # transform latitude/longitude data in degrees to pseudo-mercator coordinates in metres
    c = gpd.GeoSeries([Point(lat, long)], crs=4326)
    c = c.to_crs(3857)
    return c
dataframe_sedes["DISTANCIA_SEDES"] = dataframe_sedes.apply(lambda x : to_mercator(x["LATITUD"],x["LONGITUD"]),axis=1)
dataframe_sedes

,NOMBRE,NOMBRE-VIA,DISTRITO,LATITUD,LONGITUD,DISTANCIA_SEDES
0,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,FUENCARRAL-EL PARDO,40.485508,-3.735279,POINT (4506826.154319164 -416104.2065551275)
1,Campo de Golf del Club de Golf Olivar de la Hi...,VIA DE DUBLIN,BARAJAS,40.465351,-3.611293,POINT (4504582.255355831 -402273.7208142197)
2,Campos de Fútbol Ernesto Cotorruelo,VIA LUSITANA,CARABANCHEL,40.381231,-3.724179,POINT (4495218.036163406 -414865.966552915)
3,Centro Comercial Dreams - Palacio Municipal de...,SILVANO,HORTALEZA,40.462913,-3.635734,POINT (4504310.842371287 -404999.9123872458)
4,Centro de Alto Rendimiento del Consejo Superio...,MARTIN FIERRO,MONCLOA-ARAVACA,40.436812,-3.731957,POINT (4501405.320516344 -415733.6645299961)
...,...,...,...,...,...,...
606,Piscina SAGE Fitness,ESCALONA,LATINA,40.397182,-3.761105,POINT (4496993.758844213 -418985.2758262118)
607,Pista de Patinaje Paco de Lucía,PACO DE LUCIA,DISTRITO,40.385278,-3.764155,POINT (4495668.617279258 -419325.5917997775)
608,Pista de petanca Centro de Mayores La Vaguada,MONFORTE DE LEMOS,FUENCARRAL-EL PARDO,40.479033,-3.708264,POINT (4506105.338268181 -413090.5785481936)
609,Polideportivo Antonio Magariños,SERRANO,CHAMARTIN,40.442522,-3.686096,POINT (4502040.979548661 -410617.7057179091)
610,WiZink Center,JORGE JUAN,SALAMANCA,40.423284,-3.672104,POINT (4499899.340417478 -409056.8845014666)

YA TENEMOS LOS DOS DATAFRAMES LISTOS PARA COMPRARLOS:

- dataframe_final1 = contiene los datos de todas las estaciones de madrid y sus direcciones. 
- dataframe_final2 = contiene los datos de todos los centros deportivos de madrid y sus direcciones.

vamos a comparar la latitud y longitud de cada una de las filas del dataframe_final2, con todo el dataframe_final1, y nos quedaremos con la distancia minima.


Haremos un bucle de un bucle:

for fila in dataframe_final2:(recorremos todo el dataframe_final2, elemento a elemento)
     
     for

In [80]:
#VAMOS A HACER EL MERGE DE LAS DOS TABLAS PARA QUE ME SAQUE TODAS LAS POSIBILIDADES CON UN MERGE ENTRE LAS DOS TABLAS.
dataframe_total = pd.merge(dataframe_sedes,dataframe_bicis, how = "cross")  #PARA PODER JUNTAR LAS DOS TABLAS CON TODAS LAS OPCIONES POSIBLES.
#dataframe_total
dataframe_total["TIPO DE LUGAR"] = "SEDES. Centros con espacios deportivos"
dataframe_total["DISTANCIA TOTAL"] = 0 #dataframe_total.apply(lambda x: distance_meters(x["LATITUD_y"],x["LONGITUD_y"],x["LATITUD_x"],x["LONGITUD_x"]) )  #PARA CREAR ESA COLUMNA, COMO METEMOS MAS DE UN ARGUMENTO

dataframe_total2 = dataframe_total[["NOMBRE","NOMBRE-VIA","TIPO DE LUGAR","DISTRITO","DISTANCIA_SEDES","name","address","DISTANCIA_BICIS","DISTANCIA TOTAL"]]
dataframe_total2

,NOMBRE,NOMBRE-VIA,TIPO DE LUGAR,DISTRITO,DISTANCIA_SEDES,name,address,DISTANCIA_BICIS,DISTANCIA TOTAL
0,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Puerta del Sol A,Puerta del Sol nº 1,POINT (4499223.648366921 -412373.2851572837),0
1,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Puerta del Sol B,Puerta del Sol nº 1,POINT (4499234.670122574 -412347.498528782),0
2,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Miguel Moya,Calle Miguel Moya nº 1,POINT (4499599.340516399 -412820.3206106317),0
3,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,POINT (4500679.707306497 -412940.3068148262),0
4,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Malasaña,Calle Manuela Malasaña nº 5,POINT (4500485.866677178 -412457.3286497012),0
...,...,...,...,...,...,...,...,...,...
161299,WiZink Center,JORGE JUAN,SEDES. Centros con espacios deportivos,SALAMANCA,POINT (4499899.340417478 -409056.8845014666),Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,POINT (4502177.655770458 -415179.5220676512),0
161300,WiZink Center,JORGE JUAN,SEDES. Centros con espacios deportivos,SALAMANCA,POINT (4499899.340417478 -409056.8845014666),Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,POINT (4502140.920338497 -415172.8287427756),0
161301,WiZink Center,JORGE JUAN,SEDES. Centros con espacios deportivos,SALAMANCA,POINT (4499899.340417478 -409056.8845014666),Facultad Biología,Calle José Antonio Novais frente al nº 12,POINT (4502687.743941171 -415213.4906984274),0
161302,WiZink Center,JORGE JUAN,SEDES. Centros con espacios deportivos,SALAMANCA,POINT (4499899.340417478 -409056.8845014666),Facultad Derecho,Avenida Complutense nº 23,POINT (4502994.74083288 -415445.024322674),0
161303,WiZink Center,JORGE JUAN,SEDES. Centros con espacios deportivos,SALAMANCA,POINT (4499899.340417478 -409056.8845014666),Zurbano,Calle Zurbano nº 90,POINT (4501578.756909991 -411366.6317244973),0

In [81]:
from shapely.geometry import Point
import geopandas as gpd 
def distance_meters(DISTANCIA_SEDES, DISTANCIA_BICIS):
    # return the distance in metres between to latitude/longitude pair point in degrees (i.e.: 40.392436 / -3.6994487)
    
    return DISTANCIA_SEDES.distance(DISTANCIA_BICIS)

dataframe_total2["DISTANCIA TOTAL"] =  dataframe_total2.apply(lambda x: distance_meters(x["DISTANCIA_SEDES"],x["DISTANCIA_BICIS"]),axis=1 )
dataframe_total2

/Users/PabloMontesGrande/miniconda3/envs/proyecto1/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,NOMBRE,NOMBRE-VIA,TIPO DE LUGAR,DISTRITO,DISTANCIA_SEDES,name,address,DISTANCIA_BICIS,DISTANCIA TOTAL
0,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Puerta del Sol A,Puerta del Sol nº 1,POINT (4499223.648366921 -412373.2851572837),8468.640459
1,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Puerta del Sol B,Puerta del Sol nº 1,POINT (4499234.670122574 -412347.498528782),8470.152744
2,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Miguel Moya,Calle Miguel Moya nº 1,POINT (4499599.340516399 -412820.3206106317),7937.930753
3,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,POINT (4500679.707306497 -412940.3068148262),6912.964085
4,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Malasaña,Calle Manuela Malasaña nº 5,POINT (4500485.866677178 -412457.3286497012),7314.298725
...,...,...,...,...,...,...,...,...,...
161299,WiZink Center,JORGE JUAN,SEDES. Centros con espacios deportivos,SALAMANCA,POINT (4499899.340417478 -409056.8845014666),Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,POINT (4502177.655770458 -415179.5220676512),6532.795084
161300,WiZink Center,JORGE JUAN,SEDES. Centros con espacios deportivos,SALAMANCA,POINT (4499899.340417478 -409056.8845014666),Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,POINT (4502140.920338497 -415172.8287427756),6513.789566
161301,WiZink Center,JORGE JUAN,SEDES. Centros con espacios deportivos,SALAMANCA,POINT (4499899.340417478 -409056.8845014666),Facultad Biología,Calle José Antonio Novais frente al nº 12,POINT (4502687.743941171 -415213.4906984274),6758.623682
161302,WiZink Center,JORGE JUAN,SEDES. Centros con espacios deportivos,SALAMANCA,POINT (4499899.340417478 -409056.8845014666),Facultad Derecho,Avenida Complutense nº 23,POINT (4502994.74083288 -415445.024322674),7098.579725
161303,WiZink Center,JORGE JUAN,SEDES. Centros con espacios deportivos,SALAMANCA,POINT (4499899.340417478 -409056.8845014666),Zurbano,Calle Zurbano nº 90,POINT (4501578.756909991 -411366.6317244973),2855.761193

In [91]:

#ahora tenemos que hacer un input para que el usuario meta la direccion que el quiera, y me de la estacion de bicimad mas cercana a la direccion que el usuario meta.

def bicimad_mas_cercana():
    i = str(input("Introduzca lugar"))
    a = dataframe_total2[dataframe_total2["NOMBRE"] == i]
    return a.sort_values(by = "DISTANCIA TOTAL", ascending = True).head(1)
bicimad_mas_cercana()

,NOMBRE,NOMBRE-VIA,TIPO DE LUGAR,DISTRITO,DISTANCIA_SEDES,name,address,DISTANCIA_BICIS,DISTANCIA TOTAL
262,Campo de Golf del Centro Nacional de Golf,ARROYO DEL MONTE,SEDES. Centros con espacios deportivos,FUENCARRAL-EL PARDO,POINT (4506826.154319164 -416104.2065551275),Facultad Derecho,Avenida Complutense nº 23,POINT (4502994.74083288 -415445.024322674),3887.705045

In [1]:
#AHORA QUEREMOS QUE NOS SAQUE TODAS LAS ESTACIONES PARA CADA UNA DE LAS DIRECCIONES, POR LO TANTO LO UNICO QUE TENEMOS QUE HACER ES QUITAR EL HEAD()


def todas_las_estaciones():
    i = str(input("Introduzca lugar"))
    a = dataframe_total2[dataframe_total2["NOMBRE"] == i]
    return a.sort_values(by = "DISTANCIA TOTAL", ascending = True)
todas_las_estaciones()

NameError: name 'dataframe_total2' is not defined

In [89]:
#AHORA VAMOS A GUARDAR TODAS LAS TABLAS QUE YA HEMOS HECHO COMO CSV O COMO JSON COMO QUERAMOS, EN LA MISMA CARPETA DONDE TENEMOS LAS BASES DE DATOS.

#METODO PARA SABER QUE TENEMOS EN CADA CARPETA:

os.listdir("../DATA")  #ahi es donde vamos a guardar las 3 tablas que tenemos, en nuestro caso las vamos a guardar como json.



dataframe_sedes.to_csv("../DATA/dataframe_sedes.csv")
dataframe_bicis.to_csv("../DATA/dataframe_bicis.csv")


dataframe_total2.to_csv("../DATA/dataframe_total2.csv")

#YA TENEMOS LAS 3 TABLAS IMPORTANTES GUARDADAS COMO ARCHIVOS CSV

In [ ]:
#AHORA UNA VEZ QUE TODO ESTA HECHO LO QUE TENEMOS QUE HACER SON LAS FUNCIONES PARA CADA PASO QUE HEMOS DADO AQUI, Y DESPUES DE ESO HACER EL PIPELINE SOLO CON LAS FUNCIONES.